# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'menuofcircles' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘CircleMenu’

  # Pods for menuofcircles

  target 'menuofcirclesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'menuofcirclesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
